export const devicesList = [
  {
    id: "dev_1",
    name: "Main Gateway",
    user: "Clint R.",
    signal: "Strong",
    batteryMin: 18,
    status: "Stable",
  },
  {
    id: "dev_2",
    name: "Portable Gateway",
    user: "Warehouse 2",
    signal: "Stable",
    batteryMin: 75,
    status: "Problem",
  },
  {
    id: "dev_3",
    name: "John’s iPhone 12 Pro",
    user: "John V.",
    signal: "Strong",
    batteryMin: 71,
    status: "Active",
  },
  {
    id: "dev_4",
    name: "Command Center PC",
    user: "Olivia S.",
    signal: "Internet",
    batteryMin: 100,
    status: "Problem",
  },
  {
    id: "dev_5",
    name: "Rescue Team Tablet",
    user: "Amit R.",
    signal: "Weak",
    batteryMin: 22,
    status: "Problem",
  },
  {
    id: "dev_6",
    name: "Medical Camp Router",
    user: "Relief Camp A",
    signal: "Stable",
    batteryMin: 56,
    status: "Stable",
  },
  {
    id: "dev_7",
    name: "Satellite Phone X3",
    user: "Neha S.",
    signal: "Internet",
    batteryMin: 90,
    status: "Active",
  },
  {
    id: "dev_8",
    name: "Flood Zone Mesh Node",
    user: "Zone B Control",
    signal: "Weak",
    batteryMin: 12,
    status: "Problem",
  },
  {
    id: "dev_9",
    name: "Volunteer iPad Mini",
    user: "Sara K.",
    signal: "Strong",
    batteryMin: 64,
    status: "Active",
  },
  {
    id: "dev_10",
    name: "Emergency Ops Laptop",
    user: "District HQ",
    signal: "Internet",
    batteryMin: 48,
    status: "Stable",
  },
];
